# fly.toml app configuration file generated for nest-app on 2025-01-10T15:17:27+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nest-app'
primary_region = 'sin'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[env]
  PORT = "3000"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
